A/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls',namespace='home')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('orders/',include('orders.urls',namespace='orders')),
] 

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path,include,re_path
from . import views


app_name = 'home'




bucket_urls = [
	 path('', views.upload_photo, name='upload_photo'),
    re_path(r'^download/(?P<photo_name>.+)/$', views.download_photo, name='download_photo'),
    re_path(r'^delete/(?P<photo_name>.+)/$', views.delete_photo, name='delete_photo'),  # Update this line
]

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('category/<slug:category_slug>/', views.HomeView.as_view(), name='category_filter'),
    path('bucket/',include(bucket_urls)),
    path('product/<slug:slug>', views.DetailView.as_view(), name='detail'),

]

orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'

urlpatterns = [
    path('create/',views.CreateOrderView.as_view(),name='order_create'),
    path('detail/<int:order_id>',views.DetailOrderView.as_view(),name='order_detail'),
    path('cart/',views.CartView.as_view(),name='cart'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
    path('cart/decrement/<int:product_id>/', views.CartDecrementView.as_view(), name='cart_decrement'),
    path('cart/incriment/<int:product_id>/', views.CartincrementView.as_view(), name='cart_increment'),
]

home/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify




class Category(models.Model):
    sub_category = models.ForeignKey('self', on_delete=models.CASCADE, related_name='scategory', null=True, blank=True)
    is_sub = models.BooleanField(default=False)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Mata:
        ordering = ('name',)
        verbose_name = 'my_category'
        verbose_name_plural = "categories"
    
    def __str__(self):
        return self.name


    def get_absolute_url(self):
        return reverse("home:category_filter", args=[self.slug])
    

class Product(models.Model):
    category = models.ManyToManyField(Category,related_name='products')
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    image = models.ImageField()
    description = models.CharField(max_length=200)
    price = models.IntegerField(default=0)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse("home:detail", kwargs={"slug": self.slug})
    

home/forms.py
from django import forms
from .models import Product,Category



class PhotoForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['image']
    def clean_price(self):
        price = self.cleaned_data['price']
        if not price:
            price = 0  # or any default value
        return price
    

home/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.views import View
from .models import Product,Category
from accounts.models import User
from django.conf import settings as s
from .forms import PhotoForm
from django.contrib.auth.mixins import UserPassesTestMixin,LoginRequiredMixin
from django.contrib.auth.decorators import user_passes_test
from utils import test_func
from orders.forms import CartFrom
import boto3
import datetime
import os





LIARA = {
    'endpoint': s.LIARA_ENDPOINT,
    'accesskey': s.LIARA_ACCESS_KEY,
    'secretkey': s.LIARA_SECRET_KEY,
    'bucket': s.LIARA_BUCKET_NAME
}


class HomeView(View):
    def get(self,request,category_slug=None):
        products = Product.objects.filter(available=True) 
        categories = Category.objects.filter(is_sub=False)
        if category_slug:
            categoriy = Category.objects.get(slug=category_slug)
            products = products.filter(category=categoriy)
        return render(request,'home/home.html',{'products':products,'categories':categories})
    def post(self,request):
        pass

class DetailView(View):
    def get(self,request,slug):
        products = get_object_or_404(Product,slug=slug)
        form = CartFrom
        return render(request,'home/detail.html',{'product':products,'form':form})
      

      
@user_passes_test(test_func)
def upload_photo(request):
    if request.method == 'POST':
        form = PhotoForm(request.POST, request.FILES)
        if form.is_valid():
            photo_instance = form.save(commit=False)

            default_category = Category.objects.get(id=2)
            # Get the original filename and extension
            
            photo_instance.category = default_category
            original_filename, file_extension = os.path.splitext(photo_instance.image.name)
            
            # Get current date and time
            current_date = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
            
            # Construct unique filename with date and original filename
            filename = f"{current_date}_{original_filename}{file_extension}"
            
            # Set the filename
            photo_instance.image.name = filename
            photo_instance.save()
            return redirect('home:bucket')
    else:
        form = PhotoForm()

    # Retrieve a list of uploaded photos from the S3 bucket
    s3 = boto3.client('s3',
        endpoint_url=LIARA['endpoint'],
        aws_access_key_id=LIARA['accesskey'],
        aws_secret_access_key=LIARA['secretkey']
    )
    bucket_name = LIARA['bucket']
    objects = s3.list_objects(Bucket=bucket_name)

    uploaded_photos = []
    if 'Contents' in objects:
        for obj in objects['Contents']:
            uploaded_photos.append({
                'name': obj['Key'],  # Assuming key name as file name
                'permanent_link': f"{LIARA['endpoint']}/{bucket_name}/{obj['Key']}",
                'temporary_link': s3.generate_presigned_url(
                    'get_object',
                    Params={'Bucket': bucket_name, 'Key': obj['Key']},
                    ExpiresIn=3600  # 1 hour expiry
                )
            })
    else:
        uploaded_photos.append({'name': 'no file', 'permanent_link': '', 'temporary_link': ''})

    return render(request, 'home/upload.html', {'form': form, 'uploaded_photos': uploaded_photos})


@user_passes_test(test_func)
def download_photo(request, photo_name):
    s3 = boto3.client('s3',
        endpoint_url=LIARA['endpoint'],
        aws_access_key_id=LIARA['accesskey'],
        aws_secret_access_key=LIARA['secretkey']
    )
    bucket_name = LIARA['bucket']
    file_url = s3.generate_presigned_url(
        'get_object',
        Params={'Bucket': bucket_name, 'Key': photo_name},
        ExpiresIn=3600  # 1 hour expiry
    )
    return redirect(file_url)


@user_passes_test(test_func)
def delete_photo(request, photo_name):
    s3 = boto3.client('s3',
        endpoint_url=LIARA['endpoint'],
        aws_access_key_id=LIARA['accesskey'],
        aws_secret_access_key=LIARA['secretkey']
    )
    bucket_name = LIARA['bucket']
    s3.delete_object(Bucket=bucket_name, Key=photo_name)
    return redirect('upload_photo')

home/templates/home/detail.html
{% extends "base.html" %}

{% block content %}
    <h2>{{product.name}}</h2>
    <hr>
    <figure class="figure"> 
        <img src="{{product.image.url}}" width="400" height="500" class="figure-img img-fluid rounded" alt="...">
        <figcaption class="figure-caption">{{product.created}}</figcaption>
      </figure>
    <hr>
    <p>{{product.price}}</p>
    <br>
    <form action="{% url 'orders:cart_add' product.id %}" method="post">
    {% csrf_token %}
    {{ form }}
        <input type="submit" value="add">
    </form>

{% endblock content %}

home/templates/home/home.html
{% extends "base.html" %}
{% comment %} {% load static %} {% endcomment %}
{% block content %}
    {% if user.is_authenticated %}
        {{user.full_name}}
    {% endif %}
    <br>
    
    {% for p in products %}
   
    <div class="card" style="width: 18rem; display: inline-block;" >
        <img src="{{p.image.url}}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">{{p.name}}</h5>
            <p class="card-text">{{p.description}}</p>
            <a href="{{p.get_absolute_url}}" class="btn btn-primary">Go somewhere</a>
        </div>
    </div>
    
    {% endfor %}
{% endblock content %}

home/templates/home/upload.html
{% extends "base.html" %}
{% load static %}

{% block extera_headers %}
<link rel="stylesheet" href="{% static 'home/css/style.css' %}">

{% endblock  %}

{% block content %}
<h2>Upload Photo</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
</form>

<h3>Uploaded Files</h3>
<ul>
    {% for photo in uploaded_photos %}
    <li>
        <strong>{{ photo.name }}</strong>: 
        <a href="{{ photo.permanent_link }}" target="_blank">Permanent Link</a>
        |
        <a href="{{ photo.temporary_link }}" target="_blank">Temporary Link</a>
        |
        <a href="{% url 'home:download_photo' photo.name|urlencode %}">Download</a>
        |
        <a href="{% url 'home:delete_photo' photo.name %}">Delete</a>  <!-- Ensure this line is correct -->
    </li>
    {% endfor %}
</ul>


{% endblock content %}