A/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls',namespace='home')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('orders/',include('orders.urls',namespace='orders')),
] 

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path,include,re_path
from . import views


app_name = 'home'




bucket_urls = [
	 path('', views.upload_photo, name='upload_photo'),
    re_path(r'^download/(?P<photo_name>.+)/$', views.download_photo, name='download_photo'),
    re_path(r'^delete/(?P<photo_name>.+)/$', views.delete_photo, name='delete_photo'),  # Update this line
]

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('category/<slug:category_slug>/', views.HomeView.as_view(), name='category_filter'),
    path('bucket/',include(bucket_urls)),
    path('product/<slug:slug>', views.DetailView.as_view(), name='detail'),

]

orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'

urlpatterns = [
    path('create/',views.CreateOrderView.as_view(),name='order_create'),
    path('detail/<int:order_id>',views.DetailOrderView.as_view(),name='order_detail'),
    path('cart/',views.CartView.as_view(),name='cart'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
    path('cart/decrement/<int:product_id>/', views.CartDecrementView.as_view(), name='cart_decrement'),
    path('cart/incriment/<int:product_id>/', views.CartincrementView.as_view(), name='cart_increment'),
]

orders/models.py
from django.db import models
from home.models import Product
from django.contrib.auth import get_user_model


class Order(models.Model):
    user = models.ForeignKey(get_user_model(),on_delete=models.CASCADE,related_name='order')
    paid = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('paid','-updated')

    def __str__(self):
        return f'{self.user} - {self.id}'
    def get_total_price(self):
        return sum(item.get_price() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order,on_delete=models.CASCADE,related_name='items')
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    price = models.IntegerField()
    quantity = models.IntegerField(default=1)


    def __str__(self):
        return f'{self.id}'
    def get_price(self):
        return self.price * self.quantity

orders/forms.py
from django import forms



class CartFrom(forms.Form):
    quantity = forms.IntegerField(min_value=1,max_value=9)

orders/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.views import View
from .cart import Cart
from .forms import CartFrom
from home.models import Product
from orders.models import OrderItem,Order
from django.contrib.auth.mixins import LoginRequiredMixin
from .tasks import order_created
class CartView(View):
    def get(self,request):
        cart = Cart(request)
        return render(request,'orders/cart.html',{'cart':cart})

class CartAddView(View):
    def post(self,request,product_id):
        cart = Cart(request)
        product = get_object_or_404(Product,id=product_id)
        form = CartFrom(request.POST)
        if form.is_valid():
            cart.add(product,form.cleaned_data['quantity'])
        return redirect('orders:cart')


class CartRemoveView(View):
    def get(self,request,product_id):
        cart = Cart(request)
        product = get_object_or_404(Product,id=product_id)
        cart.delete(product)
        return redirect('orders:cart')

class CartDecrementView(View):
    def get(self,request,product_id):
        cart = Cart(request)
        product = get_object_or_404(Product,id=product_id)
        cart.decrement(product)
        return redirect('orders:cart')
class CartincrementView(View):
    def get(self,request,product_id):
        cart = Cart(request)
        product = get_object_or_404(Product,id=product_id)
        cart.incriment(product)
        return redirect('orders:cart')


class DetailOrderView(LoginRequiredMixin,View):
    def get(self,request,order_id):
        order = get_object_or_404(Order,id=order_id)
        return render(request,'orders/order.html',{'order':order})


class CreateOrderView(LoginRequiredMixin,View):
    def get(self,request):
        cart = Cart(request)
        order = Order.objects.create(user=request.user)
        for item in cart:
            OrderItem.objects.create(order=order,product=item['product'],price=item['price'],quantity=item['quantity'])
        cart.clear()
        order_created.delay(order.id)
        return redirect('orders:order_detail',order.id)

orders/templates/orders/cart.html
{% extends "base.html" %}
{% load static %}

{% block content %}




<div class="breadcrumb-wrap">
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url "home:home" %}">Home</a></li>
            <li class="breadcrumb-item"><a href="{% url "home:home" %}">Products</a></li>
            <li class="breadcrumb-item active">Cart</li>
        </ul>
    </div>
</div>
<div class="cart-page">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-8">
                <div class="cart-page-inner">
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead class="thead-dark">
                                <tr>
                                    <th></th>
                                    <th>Product</th>
                                    <th>Unit Price</th>
                                    <th>Quantity</th>
                                    <th>Total</th>
                                    <th>Remove</th>
                                </tr>
                            </thead>
                            <tbody class="align-middle">
                            {% for item in cart %}


                            <tr>
                                    <th scope="row">{{ forloop.counter }}
                                    <td>
                                        <div class="img">
{#                                            <a href="#"><img src="img/product-1.jpg" alt="Image"></a>#}
                                            <p>{{ item.product.name}}</p>
                                        </div>
                                    </td>
                                    <td>{{item.product.price}}</td>
                                    <td>
                                        <div class="qty" >
                                            <button class="btn-minus" data-href="{% url 'orders:cart_decrement' item.product.id %}">
                                                <i class="fa fa-minus"></i>
                                            </button>
                                            <input type="text" value="{{ item.quantity }}">
                                            <button class="btn-plus" data-href="{% url 'orders:cart_increment' item.product.id %}" ><i class="fa fa-plus"></i></button>
                                        </div>
                                    </td>
                                    <td>{{item.total_price}}</td>
                                    <td><a type="submit" href="{% url 'orders:cart_remove' item.product.id%}" >
                                        <i class="fa fa-trash"></i></a></td>
                                </tr>
                            {% endfor %}


                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="cart-page-inner">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="coupon">
                                <input type="text" placeholder="Coupon Code">
                                <button>Apply Code</button>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="cart-summary">
                                <div class="cart-content">
                                    <h1>Cart Summary</h1>
                                    <p>Sub Total<span></span></p>
                                    <p>Shipping Cost<span>$1</span></p>
                                    <h2>Grand Total:
                                        <span>{{ cart.get_total_price }}</span>
                                    </h2>
                                </div>
                                <div class="cart-btn">
                                    <button>Update Cart</button>
                                    <a href="{% url 'orders:order_create' %}">Checkout</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="{% static 'orders/js/cart.js' %}"></script>

{% endblock content %}

orders/templates/orders/order.html
{% extends "base.html" %}


{% block content %}

<h3>Checkout</h3>
    <p>Total: {{ order.get_total_price }}</p>
{#    {% url 'orders:order_pay' order.id %}#}
    <a href="" class="btn btn-primary">Pay</a>
<br><br>
{#    {% url 'orders:apply_coupon' order.id %}#}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Apply">
    </form>

{% endblock content %}