A/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls',namespace='home')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('orders/',include('orders.urls',namespace='orders')),
] 

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('register/',views.RegisterView.as_view(),name='user_register'),
    path('verfycode/',views.VerfyCodeView.as_view(),name='user_verfy'),
    path('login/',views.LoginView.as_view(),name='user_login'),
    path('logout/',views.LogoutView.as_view(),name='user_logout'),
]

home/urls.py
from django.urls import path,include,re_path
from . import views


app_name = 'home'




bucket_urls = [
	 path('', views.upload_photo, name='upload_photo'),
    re_path(r'^download/(?P<photo_name>.+)/$', views.download_photo, name='download_photo'),
    re_path(r'^delete/(?P<photo_name>.+)/$', views.delete_photo, name='delete_photo'),  # Update this line
]

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('category/<slug:category_slug>/', views.HomeView.as_view(), name='category_filter'),
    path('bucket/',include(bucket_urls)),
    path('product/<slug:slug>', views.DetailView.as_view(), name='detail'),

]

orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'

urlpatterns = [
    path('create/',views.CreateOrderView.as_view(),name='order_create'),
    path('detail/<int:order_id>',views.DetailOrderView.as_view(),name='order_detail'),
    path('cart/',views.CartView.as_view(),name='cart'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
    path('cart/decrement/<int:product_id>/', views.CartDecrementView.as_view(), name='cart_decrement'),
    path('cart/incriment/<int:product_id>/', views.CartincrementView.as_view(), name='cart_increment'),
]

templates/inc/header.html
{% load static %}



<div class="header">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3 offset-md-9">
                <nav class="navbar bg-light">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url "home:home" %}"><i class="fa fa-home"></i>Home</a>
                        </li>
                        {% for category in categories %}
    
                        {% comment %} <li class="nav-item">
                            <a class="nav-link" href="#"><i class="fa fa-shopping-bag"></i>Best Selling</a>
                        </li> {% endcomment %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ category.get_absolute_url }}"><i class="fa fa-{{category.name}}"></i>{{category.name}}</a>
                        </li>
                    {% endfor %}

                        {% comment %} <li class="nav-item">
                            <a class="nav-link" href="#"><i class="fa fa-female"></i>Fashion & Beauty</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#"><i class="fa fa-child"></i>Kids & Babies Clothes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#"><i class="fa fa-tshirt"></i>Men & Women Clothes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#"><i class="fa fa-mobile-alt"></i>Gadgets & Accessories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#"><i class="fa fa-microchip"></i>Electronics & Accessories</a>
                        </li> {% endcomment %}
                    </ul>
                </nav>
            </div>
            {% comment %} <div class="col-md-6">
                <div class="header-slider normal-slider">
                    <div class="header-slider-item">
                        <img src="{% static "img/slider-1.jpg" %}" alt="Slider Image" />
                        <div class="header-slider-caption">
                            <p>Some text goes here that describes the image</p>
                            <a class="btn" href=""><i class="fa fa-shopping-cart"></i>Shop Now</a>
                        </div>
                    </div>
                    <div class="header-slider-item">
                        <img src="{% static "img/slider-2.jpg" %}" alt="Slider Image" />
                        <div class="header-slider-caption">
                            <p>Some text goes here that describes the image</p>
                            <a class="btn" href=""><i class="fa fa-shopping-cart"></i>Shop Now</a>
                        </div>
                    </div>
                    <div class="header-slider-item">
                        <img src="{% static "img/slider-3.jpg" %}" alt="Slider Image" />
                        <div class="header-slider-caption">
                            <p>Some text goes here that describes the image</p>
                            <a class="btn" href=""><i class="fa fa-shopping-cart"></i>Shop Now</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="header-img">
                    <div class="img-item">
                        <img src="{% static "img/category-1.jpg" %}" />
                        <a class="img-text" href="">
                            <p>Some text goes here that describes the image</p>
                        </a>
                    </div>
                    <div class="img-item">
                        <img src="{% static "img/category-2.jpg" %}" />
                        <a class="img-text" href="">
                            <p>Some text goes here that describes the image</p>
                        </a>
                    </div>
                </div>
            </div> {% endcomment %}
        </div>
    </div>
</div>
<!-- Main Slider End -->  

templates/inc/messages.html
{% load static %}

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

{% block extra_headers %}
<link href="{% static 'A/css/style.css' %}" rel="stylesheet">
<script src="{% static 'A/js/main.js' %}" ></script>
{% endblock extra_headers %}

{% if messages %}
<div class="messages">
    {% for message in messages %}
        <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

templates/inc/navbar.html
<!-- Nav Bar Start -->
<div class="nav">
    <div class="container-fluid">
        <nav class="navbar navbar-expand-md bg-dark navbar-dark">
            <a href="#" class="navbar-brand">MENU</a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                <div class="navbar-nav mr-auto">
                    <a href="product-list.html" class="nav-item nav-link">Products</a>
                    <a href="product-detail.html" class="nav-item nav-link">Product Detail</a>
                    <a href="{% url "orders:cart" %}" class="nav-item nav-link">Cart {{ cart|length }}</a>
                    <a href="checkout.html" class="nav-item nav-link">Checkout</a>
                    
                    <div class="nav-item dropdown">
                        <button class="btn btn-default dropdown-toggle nav-link" data-toggle="dropdown" style="background-color: #FF6F61;">
                            Tutorials <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                            {% for category in categories %}
                                <li class="dropdown-submenu">
                                    <a class="dropdown-item" tabindex="-1" href="{{ category.get_absolute_url }}">{{ category.name }}</a>
                                    <ul class="dropdown-menu">
                                        {% for sub in category.scategory.all %}
                                            <li><a class="dropdown-item" href="{{ sub.get_absolute_url }}">{{ sub.name }}</a></li>
                                        {% endfor %}
                                    </ul>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>

                    {% if request.user.is_authenticated %}
                        <a href="my-account.html" class="nav-item nav-link">My Account</a>
                        <div class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">User Account</a>
                            <div class="dropdown-menu">
                                <a href="{% url 'accounts:user_logout' %}" class="dropdown-item">Logout</a>
                            </div>
                        </div>
                    {% else %}
                        <div class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">More Pages</a>
                            <div class="dropdown-menu">
                                <a href="{% url 'accounts:user_login' %}" class="dropdown-item">Login</a>
                                <a href="{% url 'accounts:user_register' %}" class="dropdown-item">Register</a>
                            </div>
                        </div>
                    {% endif %}
                </div>
                <div class="navbar-nav ml-auto">
                    <!-- Add any additional nav items here -->
                </div>
            </div>
        </nav>
    </div>
</div>
<!-- Nav Bar End -->   

<!-- Scripts -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

<script>
    $(document).ready(function(){
        $('.dropdown-submenu > a').on("click", function(e){
            var $submenu = $(this).next('ul');
            e.preventDefault();
            $submenu.toggle();
            
        });
    });
    

</script>

templates/inc/top-bar.html
{% load static %}

<div class="top-bar">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6">
                <i class="fa fa-envelope"></i>
                support@email.com
            </div>
            <div class="col-sm-6">
                <i class="fa fa-phone-alt"></i>
                +012-345-6789
            </div>
        </div>
    </div>
</div>


<div class="bottom-bar">
    <div class="container-fluid">
        <div class="row align-items-center">
            <div class="col-md-3">
                <div class="logo">
                    <a href="{% url "home:home" %}">
                        <img src="{% static "img/logo.png" %}" alt="Logo">
                    </a>
                </div>
            </div>
            <div class="col-md-6">
                <div class="search">
                    <input type="text" placeholder="Search">
                    <button><i class="fa fa-search"></i></button>
                </div>
            </div>
            <div class="col-md-3">
                <div class="user">
                    <a href="wishlist.html" class="btn wishlist">
                        <i class="fa fa-heart"></i>
                        <span>(0)</span>
                    </a>
                    <a href="cart.html" class="btn cart">
                        <i class="fa fa-shopping-cart"></i>
                        <span>(0)</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>